# DNA Methylation Markings with Bismark

### Commands

after installing Bismark and downloading appropriate files to ~/qbb2020-answers/qbl-week6/ and working in the qbb2020-answers directory:

    bismark_genome_preparation qbl-week6

map bisulfite seq to genome:

    bismark qbl-week6 -1 qbl-week6/SRR3083926_1.chr6.fastq -2 qbl-week6/SRR3083926_2.chr6.fastq
    bismark qbl-week6 -1 qbl-week6/SRR3083929_1.chr6.fastq -2 qbl-week6/SRR3083929_2.chr6.fastq

sort bam files:

    samtools sort SRR3083926_1.chr6_bismark_bt2_pe.bam -o sorted.bismark.SRR3083926_1.bam
    samtools index sorted.bismark.SRR3083926_1.bam
    samtools sort SRR3083929_1.chr6_bismark_bt2_pe.bam -o sorted.bismark.SRR3083929_1.bam
    samtools index sorted.bismark.SRR3083929_1.bam

Extract methylation data:

    bismark_methylation_extractor sorted.bismark.SRR3083926_1.bam sorted.bismark.SRR3083929_1.bam -bedgraph -comprehensive

# Find methylation fold change

For each gene, find the fold change in *total methylation signal from E4 to E5 cells. If the *total methylation for a gene in E4 is zero, skip it. (Hint: you can use the python module gzip to open the bedgraph files without unzipping them.)

In [1]:
import sys
import numpy as np
import pandas as pd

In [2]:
ref = open("mm10_refseq_genes_chr6_50M_60M.bed")
E4 = open("sorted.bismark.SRR3083926_1.bedGraph")
E5 = open("sorted.bismark.SRR3083929_1.bedGraph")

E4_dict = {} 

# first, find the sum of the methylation values for E4 genes
for line in ref:
    col = line.split('\t')
    E4_val = 0 #set or reset the value of methylation counts
    gname = col[12] #gene name column
    start_val = int(col[4]) # base-pair start value
    end_val = int(col[5]) #base-pair end value
    for line2 in E4: #check genes from reference against E4 methylation data
        if "track" in line2: #skip header
            continue
        else:
            col2 = line2.split()
            #now check if methylated base-pair number is within the gene:
            if int(col2[1]) >= start_val and int(col2[1]) <= end_val: #int(col2[1]) is the bp num of the methylation mark
                E4_val += float(col2[3]) # if yes, sum up all methylation values from this gene
                # it should be ok to just use a sum of all the methylation values, because we'll be using it as quotient
                E4_dict[gname] = E4_val # use that sum for a dict value with the gene name
    E4.seek(0)
    
print(E4_dict)

{'Mpp6': 11301.106717356719, 'Dfna5': 4360.606060606061, 'Osbpl3': 18398.48627980207, 'Cycs': 297.4747474747475, '5430402O13Rik': 3270.396825396826, '4921507P07Rik': 2457.6190476190477, 'Npvf': 400.0, 'C530044C16Rik': 7114.594294594294, 'Mir148a': 100.0, 'Gm6559': 2061.746031746032, 'Nfe2l3': 3307.9975579975585, 'Hnrnpa2b1': 440.00000000000006, 'Cbx3': 1262.7813852813852, 'Snx10': 6316.190476190478, 'Skap2': 18944.053030303025, 'Halr1': 200.0, 'Hoxa1': 0.0, 'Hotairm1': 100.0, 'Hoxa2': 16.6666666666667, 'Hoxaas2': 214.2857142857143, 'Hoxa3': 2198.8888888888887, 'Hoxa4': 33.3333333333333, 'Hoxaas3': 916.6666666666667, 'Hoxa5': 100.0, 'Hoxa6': 16.6666666666667, 'Mira': 0.0, 'Hoxa7': 200.0, 'Hoxa9': 383.3333333333333, 'Mir196b': 100.0, 'Hoxa10': 500.0, 'Hoxa11': 200.0, 'Hoxa11os': 100.0, 'Hoxa13': 100.0, 'Hottip': 383.3333333333333, 'Evx1os': 696.6666666666665, 'Evx1': 733.3333333333335, '1700094M24Rik': 673.3333333333333, 'Hibadh': 13787.686516382166, 'Tax1bp1': 7265.891330891333, 'Jazf1': 38194.753857253854, 'Gm4872': 500.0, '9430076C15Rik': 8357.753357753358, 'Creb5': 9684.285714285714, 'Tril': 933.3333333333333, 'Cpvl': 11099.910589846028, '4921529L05Rik': 3469.4805194805194, 'Chn2': 3521.3690476190477, '9130019P16Rik': 15250.156833478051, 'Prr15': 100.0, 'Wipf3': 3198.3766233766232, 'Scrn1': 3487.063492063492, 'Fkbp14': 2444.7619047619046, 'Plekha8': 4013.8852813852814, 'Mturn': 826.6017316017317, 'Znrf2': 4612.521367521368, 'Nod1': 4121.031746031746, 'Ggct': 1275.2525252525252, 'Gars': 7014.352314352315, 'Crhr2': 3302.264957264957, 'Inmt': 466.6666666666667, 'Fam188b': 16429.996392496396, 'Aqp1': 816.6666666666667, 'Ghrhr': 450.0, '6430584L05Rik': 200.0, 'Adcyap1r1': 7452.878787878787, 'Neurod6': 428.5714285714286, 'Gm3279': 358.7301587301587, 'Ccdc129': 7971.371309045222, 'Ppp1r17': 250.0, 'Pde1c': 26019.380317376344, 'Lsm5': 375.0, 'Avl9': 6512.320261437909, 'Kbtbd2': 1340.7936507936508, 'Fkbp9': 3589.7550034506557, 'Nt5c3': 3232.012987012987, 'Vmn1r4': 283.33333333333337, 'Vmn1r5': 200.0, 'Vmn1r6': 0.0, 'Vmn1r7': 233.33333333333331, 'Vmn1r8': 66.6666666666667, 'Vmn1r9': 0.0, 'Vmn1r10': 0.0, 'Vmn1r11': 50.0, 'Vmn1r12': 0.0, 'Vmn1r13': 100.0, 'Vmn1r14': 200.0, 'Vmn1r15': 100.0, 'Vmn1r17': 0.0, 'Vmn1r18': 0.0, 'Vmn1r19': 0.0, 'Ppm1k': 4887.730880230881, 'Herc6': 8396.233276912524, 'Pyurf': 953.3333333333333, 'Lancl2': 2859.285714285714, 'Vopp1': 3430.416666666666, 'Vmn1r21': 0.0, 'Vmn1r24': 0.0, 'Vmn1r25': 0.0, 'Vmn1r26': 0.0, 'Vmn1r27': 166.66666666666669, 'Vmn1r28': 0.0, 'Vmn1r29': 200.0, 'Vmn1r30': 100.0, 'Abcg2': 6541.62340505794, 'Herc3': 15869.16666666667, 'Nap1l5': 583.3333333333333, 'Fam13a': 4684.142857142857, 'Tigd2': 1026.1904761904761, 'Gprin3': 1861.8181818181818}

In [3]:
# do the same for methylation of E5 gene values

ref = open("mm10_refseq_genes_chr6_50M_60M.bed")
E4 = open("sorted.bismark.SRR3083926_1.bedGraph")
E5 = open("sorted.bismark.SRR3083929_1.bedGraph")

E5_dict = {} 

# first, find the sum of the methylation values for E4 genes
for line in ref:
    col = line.split('\t')
    E5_val = 0 #set or reset the value of methylation counts
    gname = col[12] #gene name column
    start_val = int(col[4]) # base-pair start value
    end_val = int(col[5]) #base-pair end value
    for line2 in E5: #check genes from reference against E4 methylation data
        if "track" in line2: #skip header
            continue
        else:
            col2 = line2.split()
            #now check if methylated base-pair number is within the gene:
            if int(col2[1]) >= start_val and int(col2[1]) <= end_val: #int(col2[1]) is the bp num of the methylation mark
                E5_val += float(col2[3]) # if yes, sum up all methylation values from this gene
                # it should be ok to just use a sum of all the methylation values, because we'll be using it as quotient
                E5_dict[gname] = E5_val # use that sum for a dict value with the gene name
    E5.seek(0)
    
print(E5_dict)

{'Mpp6': 44481.33882783883, 'Dfna5': 27123.33333333334, 'Osbpl3': 110510.94061735368, 'Cycs': 2649.603174603175, '5430402O13Rik': 15001.547619047615, '4921507P07Rik': 11791.54761904762, 'Npvf': 2707.142857142857, 'C530044C16Rik': 20781.190476190477, 'Mir148a': 0.0, 'Gm6559': 9505.0, 'Nfe2l3': 14916.309523809527, 'Hnrnpa2b1': 3661.428571428571, 'Cbx3': 7402.064777327935, 'Snx10': 44283.41957749853, 'Skap2': 77765.9965728716, 'Halr1': 7539.7619047619055, 'Hoxa1': 600.0, 'Hotairm1': 200.0, 'Hoxa2': 253.3333333333334, 'Hoxaas2': 360.0, 'Hoxa3': 7075.952380952382, 'Hoxa4': 516.6666666666667, 'Hoxaas3': 2097.6190476190477, 'Hoxa5': 580.9523809523811, 'Hoxa6': 300.0, 'Mira': 91.6666666666667, 'Hoxa7': 408.33333333333337, 'Hoxa9': 1701.6666666666667, 'Mir196b': 0.0, 'Hoxa10': 420.0, 'Hoxa11': 200.0, 'Hoxa11os': 566.6666666666667, 'Hoxa13': 200.0, 'Hottip': 986.6666666666667, 'Evx1os': 1600.0, 'Evx1': 766.6666666666667, '1700094M24Rik': 4620.634920634921, 'Hibadh': 52094.329004329, 'Tax1bp1': 23511.607142857145, 'Jazf1': 169523.32728095667, 'Gm4872': 4183.333333333334, '9430076C15Rik': 52577.142857142855, 'Creb5': 72405.6069094304, 'Tril': 1966.6666666666667, 'Cpvl': 58656.91314024687, '4921529L05Rik': 22095.000000000004, 'Chn2': 17192.380952380954, '9130019P16Rik': 83851.98730651557, 'Prr15': 1400.0, 'Wipf3': 30175.714285714294, 'Scrn1': 33169.642857142855, 'Fkbp14': 9870.20202020202, 'Plekha8': 22900.555555555555, 'Mturn': 10195.0, 'Znrf2': 28335.137362637368, 'Nod1': 29267.01714951714, 'Ggct': 6094.285714285715, 'Gars': 31400.238095238103, 'Crhr2': 17620.0, 'Inmt': 1760.0, 'Fam188b': 63322.936492815745, 'Aqp1': 4783.333333333334, 'Ghrhr': 3083.3333333333335, '6430584L05Rik': 8409.761904761906, 'Adcyap1r1': 24650.55555555556, 'Neurod6': 1300.0, 'Gm3279': 3990.992063492063, 'Ccdc129': 45829.51490791085, 'Ppp1r17': 5008.333333333333, 'Pde1c': 87419.01848893591, 'Lsm5': 1906.6666666666667, 'Avl9': 26116.44957983193, 'Kbtbd2': 13270.873015873014, 'Fkbp9': 21870.714285714286, 'Nt5c3': 15286.666666666666, 'Vmn1r4': 200.0, 'Vmn1r5': 150.0, 'Vmn1r6': 133.33333333333331, 'Vmn1r7': 242.8571428571429, 'Vmn1r8': 413.3333333333333, 'Vmn1r9': 0.0, 'Vmn1r10': 325.0, 'Vmn1r11': 140.0, 'Vmn1r12': 100.0, 'Vmn1r13': 233.33333333333331, 'Vmn1r14': 483.3333333333333, 'Vmn1r15': 300.0, 'Vmn1r16': 100.0, 'Vmn1r17': 158.33333333333331, 'Vmn1r18': 100.0, 'Vmn1r20': 350.0, 'Ppm1k': 18547.597402597403, 'Herc6': 32881.55736572867, 'Pyurf': 2456.6666666666665, 'Lancl2': 10587.22222222222, 'Vopp1': 24235.46912238089, 'Vmn1r21': 100.0, 'Vmn1r22': 100.0, 'Vmn1r23': 166.66666666666669, 'Vmn1r24': 100.0, 'Vmn1r25': 0.0, 'Vmn1r26': 200.0, 'Vmn1r27': 100.0, 'Vmn1r28': 300.0, 'Vmn1r29': 200.0, 'Vmn1r30': 400.0, 'Vmn1r31': 100.0, 'Abcg2': 39075.184212003485, 'Herc3': 45737.261904761894, 'Nap1l5': 500.0, 'Fam13a': 29442.11976911977, 'Tigd2': 1966.6666666666665, 'Gprin3': 20758.27067669173}

In [4]:
#convert the dictionaries to dataframes
E4_df = pd.DataFrame(list(E4_dict.items()),columns = ['GeneName','E4_me_sum'])
E5_df = pd.DataFrame(list(E5_dict.items()),columns = ['GeneName','E5_me_sum'])

In [5]:
#merge dataframes
both_df = pd.merge(E4_df, E5_df, on=["GeneName"])
both_df

          GeneName     E4_me_sum      E5_me_sum
0             Mpp6  11301.106717   44481.338828
1            Dfna5   4360.606061   27123.333333
2           Osbpl3  18398.486280  110510.940617
3             Cycs    297.474747    2649.603175
4    5430402O13Rik   3270.396825   15001.547619
..             ...           ...            ...
103          Herc3  15869.166667   45737.261905
104         Nap1l5    583.333333     500.000000
105         Fam13a   4684.142857   29442.119769
106          Tigd2   1026.190476    1966.666667
107         Gprin3   1861.818182   20758.270677

[108 rows x 3 columns]

In [6]:
#now do the math to find fold change
both_df['FoldChange'] = (both_df['E5_me_sum'] - both_df['E4_me_sum']) / both_df['E4_me_sum']
both_df

          GeneName     E4_me_sum      E5_me_sum  FoldChange
0             Mpp6  11301.106717   44481.338828    2.936016
1            Dfna5   4360.606061   27123.333333    5.220083
2           Osbpl3  18398.486280  110510.940617    5.006524
3             Cycs    297.474747    2649.603175    7.906985
4    5430402O13Rik   3270.396825   15001.547619    3.587073
..             ...           ...            ...         ...
103          Herc3  15869.166667   45737.261905    1.882146
104         Nap1l5    583.333333     500.000000   -0.142857
105         Fam13a   4684.142857   29442.119769    5.285487
106          Tigd2   1026.190476    1966.666667    0.916473
107         Gprin3   1861.818182   20758.270677   10.149462

[108 rows x 4 columns]